# Common to [aquapis] Servers
ansible_user: pi
ansible_become: yes
# Use python3 on the raspberrypi, as python2 is deprecated and not available by default on newer raspbian versions
ansible_python_interpreter: /usr/bin/python3
