@startuml

package "atlantis (a raspberrypi)" as pi {
interface HTTP as http1
http1 - [aquametric-service] : port 8080
}

stack fishtank {
    boundary DS18B20 as sensor
}

pi -d-> sensor : wired

cloud Somewhere {
    interface HTTP as http2
    [prometheus] --> http1 : scrape values
    [grafana] -l-> [prometheus]
    [grafana] - http2 : port 8080
}
 actor Me
 Me --> http2 : Web-\nbrowser

@enduml